### PR TITLE
Update to 7.3.1

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@mattip, can a package built with 7.3.1 run with pypy 7.3.0? Or is it only the other way around?

**Comment by mattip** [comment]
As far as I know they should be interchangeable, barring bugs.

**Comment by isuruf** [comment]
I forgot that 7.3.1 introduced support for some new C API functions. So, if an extension is built with 7.3.1, we should add the constraint that at runtime 7.3.0 is not used.

**Comment by mattip** [comment]
Hmm, then it really should have been 7.4 if it is incompatible. My thinking was it only really fixes broken things, or adds missing C-API calls, so it is OK as 7.3.1

**Comment by isuruf** [comment]
7.4 with a new ABI tag is worse though. That requires all extensions be rebuilt. Only 1 or 2 ABI breakages per year for >1000 rebuilds is desirable. Anything more makes it harder to manage. We only have two other dependencies like that. cpython and r-base, both of which has a new breaking release only once per year.

**Pull request merged**
