### PR TITLE
update and add pypy3.7

### PR DESCRIPTION
**Pull request by mattip**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mattip** [comment]
@conda-forge-admin, please rerender

**Comment by mattip** [comment]
hmm, is there an example of setting a variable via a `recipe/conda_build_config.yaml`? It seems I am not successfully setting `python_version` correctly

**Comment by mattip** [comment]
@conda-forge-admin, please rerender

**Comment by mattip** [comment]
@isuruf thanks

**Comment by isuruf** [comment]
We can't update the python version here without updating the cpython versions due to conda solver preferring newer versions. @ocefpaf we have to update our python 3.6 and 3.7 recipes before merging this.

**Comment by mattip** [comment]
> we have to update our python 3.6 and 3.7 recipes before merging this.

Is that also the reason the pypy 3.7 build fails here? pypy 3.6 succeeds.
```
failed to get install actions, retrying.  exception was: Unsatisfiable dependencies for platform linux-64: \
    {'python_abi==3.7[build=*_pypy37_pp73]'}
WARNING:conda_build.build:failed to get install actions, retrying.  exception was: Unsatisfiable dependencies \
    for platform linux-64: {'python_abi==3.7[build=*_pypy37_pp73]'}
WARNING conda_build.build:test(2799): failed to get install actions, retrying.  exception was: Unsatisfiable \
    dependencies for platform linux-64: {'python_abi==3.7[build=*_pypy37_pp73]'}
Tests failed for python-3.7.9-4_73_pypy.tar.bz2 - moving package to \
    /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for python-3.7.9-4_73_pypy.tar.bz2 - moving package to \
    /home/conda/feedstock_root/build_artifacts/broken
WARNING conda_build.build:tests_failed(2895): Tests failed for python-3.7.9-4_73_pypy.tar.bz2 - moving \
    package to /home/conda/feedstock_root/build_artifacts/broken
TESTS FAILED: python-3.7.9-4_73_pypy.tar.bz2

```

**Comment by isuruf** [comment]
Ah, no. We need to update https://github.com/conda-forge/python_abi-feedstock/blob/master/recipe/conda_build_config.yaml too

**Comment by mattip** [comment]
> we have to update our python 3.6 and 3.7 recipes before merging this

Where do those live?

**Comment by isuruf** [comment]
3.6 branch and 3.7 branch of https://github.com/conda-forge/python-feedstock

**Comment by mattip** [comment]
OK, python-feedstock looks like it is above my payscale. There are ~20 open PRs there, some of them seem to be also to update the versions of 3.6, 3.7

**Comment by ocefpaf** [comment]
> OK, python-feedstock looks like it is above my payscale. There are ~20 open PRs there, some of them seem to be also to update the versions of 3.6, 3.7

I have one for Python 3.6 that is quite stale. I'll try to address this tomorrow. If I fail I'll cry for help ;-p

**Comment by mattip** [comment]
@isuruf any news about cpython 3.6/3.7?

**Comment by mattip** [comment]
@isuruf I didn't hear the cry for help yet

**Comment by mattip** [comment]
The updates to python-feedstock went in. What else needs to be done here?

**Comment by isuruf** [comment]
Thanks for the PR

**Comment by mattip** [comment]
What else needs to be done to use pypy3.7? I can create a conda environment with `conda create -n pypy3.7 pypy3.7`, but when I activate that and try to install numpy, the resolver wants to add python3.9

**Comment by isuruf** [comment]
We have to rebuild all the packages for pypy3.7 of course. I'll bring it up in the next conda-forge meeting.

**Pull request merged**
