### PR TITLE
v7.3.13 was released (for python3.9) and pypy3.6-feedstock updated

### PR DESCRIPTION
**Pull request by mattip**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Following the pattern in #29

### CODE REVIEW

**Comment by mattip** [comment]
I would like to merge this without aarch64 and ppc64le builds, there are ongoing problems with pandas that I want to see if this version fixes. If that works, I will build the aarch64 and ppc64le packages.

**Comment by mattip** [comment]
Whoops, too fast. The new packages have not percolated out yet.

**Review by h-vetinari — APPROVED** [review]

**Comment by h-vetinari** [comment]
Builds from https://github.com/conda-forge/pypy3.6-feedstock/pull/110 should be online now

**Comment by h-vetinari** [comment]
Merging this. If someone does the arch/ppc builds, all the better (though at this point, I'd consider unsupporting pypy on the arches - it's doubly niche, and given we don't have CI, it's just completely out of whack between maintenance effort and utility)

**Comment by mattip** [comment]
Thanks!

**Pull request merged**
