### PR TITLE
Update to PyPy 7.3.9

### PR DESCRIPTION
**Pull request by lithomas1**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge-admin, please restart ci

**Comment by h-vetinari** [comment]
Realised to late (sorry) - the aarch/ppc builds were failing because they're not built in CI on https://github.com/conda-forge/pypy3.6-feedstock; this needs to be done manually.

**Comment by mattip** [comment]
@conda-forge-admin, please restart ci

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
