### PR TITLE
PyPy 7.3.12

### PR DESCRIPTION
**Pull request by h-vetinari**
no more 3.8

Following https://github.com/conda-forge/pypy3.6-feedstock/pull/105

### CODE REVIEW

**Comment by mattip** [comment]
Any idea why mamba [cannot solve](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=771517&view=logs&j=4f922444-fdfe-5dcf-b824-02f86439ef14&t=937c195f-508d-5135-dc9f-d4b5730df0f7&l=425) the constraints?
```
Mamba failed to solve:
 - python 3.9.17.* 0_73_pypy
 - pypy3.9 7.3.12.*
 - python_abi 3.9.* *_pypy39_pp73

with channels:

The reported errors are:
- Encountered problems while solving:
-   - package pypy3.9-7.3.12-h9557127_2 has constraint python 3.9.* *_7.3_pypy \
-     conflicting with python-3.9.17-0_73_pypy
- 

```

**Comment by mattip** [comment]
@isuruf fixed the typo in the feedstock in conda-forge/pypy3.6-feedstock#106.

**Comment by h-vetinari** [comment]
Do we want to merge this with broken CI, or explicitly exclude 7.3.12 for aarch/ppc? (given that those arches have lower priority than other things right now, as discussed post-merge in https://github.com/conda-forge/pypy3.6-feedstock/pull/105)

CC @mattip @isuruf

**Comment by mattip** [comment]
If I understand correctly, merging this as-is will implicitly exclude 7.3.12 for aarch64/pppc64le. So the difference is whether we explicitly exclude or implictly exclude? If that is the case, I don't think it really matters one way or the other.

**Comment by mattip** [comment]
Thanks!

**Pull request merged**
